version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
      
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "get_deps.sh" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: bash get_deps.sh
            
      - save_cache:
          paths:
            - deps
          key: v1-dependencies-{{ checksum "get_deps.sh" }}      

      - run:
          name: Build
          command: make install 

      - run:
          name: Test
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip uninstall RLTest
            pip install https://github.com/lantiga/RLTest/archive/python3_fixes.zip
            python3 -m RLTest --test test/basic_tests.py --module src/redisai.so

