version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "get_deps.sh" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: bash get_deps.sh

      - save_cache:
          paths:
            - deps
          key: v1-dependencies-{{ checksum "get_deps.sh" }}

      - run:
          name: Build
          command: make install

      - run:
          name: Test
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip uninstall -y RLTest
            pip install https://github.com/lantiga/RLTest/archive/python3_fixes.zip
            pip install numpy
            pip install scikit-image
            echo "CURRENT LD_LIBRARY_PATH"
            echo $LD_LIBRARY_PATH
            python3 -m RLTest --test test/basic_tests.py --module src/redisai.so --oss-redis-path deps/redis/src/redis-server -s
          environment:
            LD_LIBRARY_PATH: $LD_LIBRARY_PATH:deps/libtensorflow/lib
  deploy_docs:
    docker:
      - image: 'redislabsmodules/rmbuilder:latest'
    steps:
      - checkout
      - run:
          name: Build Docs
          command: mkdocs build
      - run:
          name: Deploy Docs to S3
          command: >-
            aws s3 cp site s3://oss.redislabs.com/$WEBSITE_FOLDER/ --acl
            public-read --recursive
workflows:
  version: 2
  build_and_package:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy_docs:
          filters:
            branches:
              only: master
