version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
      
    steps:
      - checkout
      #- run:
      #    name: Install prerequisite
      #    command: >-
      #      apt-get update; apt-get install -y cmake curl
      - run:
          name: Deps
          command: bash get_deps.sh
      - run:
          name: Build
          command: make install 
      - run:
          name: Test
          command: python -m RLTest --test test/basic_tests.py --module src/redisai.so

