name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Submodule checkout
      run: git submodule update --init --recursive 
    - name: Install dependencies
      run: |
        git clone git://github.com/antirez/redis.git --branch 6.0; (cd redis; make malloc=libc -j $(nproc); make install); redis-server --version
        ./get_deps.sh cpu
    - name: make
      run: make -C opt all SHOW=1
    - name: Test
      run: |
        mkdir -p ~/workspace/tests
        make -C opt test SHOW=1
