on: [push]
name: Deploy redisai-cuda11-baseimage
jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    env:
      EC2_REGION: ${{ secrets.EC2_REGION }}
      EC2_ACCESS_KEY: ${{ secrets.EC2_ACCESS_KEY }}
      EC2_SECRET_KEY: ${{ secrets.EC2_SECRET_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.EC2_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.EC2_SECRET_KEY }}
    steps:
    - name: Check EC2_REGION,EC2_ACCESS_KEY,EC2_SECRET_KEY are set
      run: |
        if ${{ env.EC2_REGION == '' }} || ${{ env.EC2_ACCESS_KEY == '' }} || ${{ env.EC2_SECRET_KEY == '' }} ; then
          echo "ec2 secrets are not set"
          exit 1
        fi
    - name: Add infra key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_PRIVATE_PEM }}" > ~/.ssh/perf-cto-joint-tasks.pem
        chmod 600 ~/.ssh/perf-cto-joint-tasks.pem

    - name: Setup testing-infrastructure
      run: |
        git clone https://github.com/RedisLabsModules/testing-infrastructure --branch redisai-cuda11-baseimage
        cd testing-infrastructure
        ./install_deps.sh
        cd terraform/redisai-cuda11-baseimage
        terraform init
        terraform apply --auto-approve -var 'github_actor=${{ env.GITHUB_ACTOR }}' \
                                       -var 'github_repo=${{ env.GITHUB_REPO }}' \
                                       -var 'github_sha=${{ env.GITHUB_SHA }}'
        terraform output -json > ~/deployment_info.json
        MACHINE_EIP=$(cat ~/deployment_info.json | jq -r '.server_public_ip.value[0]')
        echo "MACHINE IP: ${MACHINE_EIP}"
    
    - name: RedisAI GPU build/test
      run: |
        echo "add test logic here"

    - name: Tear down testing-infrastructure
      run: |
        cd testing-infrastructure/terraform/redisai-cuda11-baseimage
        terraform destroy --auto-approve

      